---
title: "Temporal trends in DHW"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny
---



```{r, message=FALSE, warning=FALSE}

library(flexdashboard)
library(tidyverse)
library(ggplot2)
library(plotly)
library(leaflet)
library(sf)

# Load the data
df <- readRDS("/Users/rof011/GBR-coral-bleaching/data/gbr_shape_dhw.RDS")

# Ensure df is an sf object, you might need to adjust this based on your actual data structure
# If df is not an sf object yet, convert it accordingly
# df <- st_as_sf(df, coords = c("lon", "lat"), crs = 4326) # Example conversion, adjust as necessary

# Calculate centroids if df is an sf object
centroids <- st_centroid(df) %>% 
  st_transform(4326) %>%
  st_coordinates() %>% 
  as.data.frame() %>% 
  rename(lat = Y, lon = X)

# Add centroids back to the data
df <- cbind(df, centroids)

# Shiny UI for selecting gbr_name
selectInput("gbr_name", "Select reef(s):", choices = unique(df$gbr_name), selected = c("Heron Reef"), multiple = FALSE)



```

```{r, message=FALSE, warning=FALSE}

# Reactive expression to filter data based on selected gbr_name
filteredData <- reactive({
  df %>% 
    filter(gbr_name == input$gbr_name)
})

# Render the Leaflet map
output$map <- renderLeaflet({
  leaflet(df) %>%
    addTiles() %>%
    setView(lng = 145.3, lat = -14.5, zoom = 9)
})

# Update the map based on the selection
observe({
  data <- filteredData() # Get the filtered data
  
  if(nrow(data) > 0){
    leafletProxy("map", data = data) %>%
      addTiles() %>%
      setView(lng = data$lon[1,], lat = data$lat[1,], zoom = 9)
  }
})

leafletOutput("map")

```
